# Generated by Django 4.0.5 on 2022-06-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productphoto',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
